ボウリングのスコア計算プログラムオブジェクト指向版
a-terumoto-gs/ruby-practices pull request #10
Opened 2023-12-04 09:10 UTC by a-terumoto-gs

2023-12-08 15:20 UTC, u1tnk requested changes
指摘したところ以外にGameクラスに責務が偏り過ぎと思います。
FrameやShotができることは移譲してGameクラスを読みやすくしてみてください 💪

2023-12-08 15:20 UTC, u1tnk commented on 06.bowling_object/game.rb
> +    while index < game_shots.length
悪くは無いですが、rubyで仕事するにあたってはrubyらしく書いて欲しいです。 `times` や `each` などを使ってみてください。

2023-12-08 15:20 UTC, u1tnk commented on 06.bowling_object/game.rb
> +  def initialize(game_shot)
命名を再検討お願いします。

- Shotクラスがあるのに xxx_shot で Shotクラスのインスタンスアでは無いのは不自然。
- game_shots / game_shot が同じメソッドにあるのであれば game_shotが入っている配列が game_shots と思ってしまいます。

2023-12-08 15:20 UTC, u1tnk commented on 06.bowling_object/shot.rb
> +  attr_reader :mark
これを呼ん でいる箇所はありますでしょうか？
必要で無い変数を外部に公開するのはプログラムのシンプルさを下げて混乱のもとになるので不要であれば消しましょう。

2023-12-08 15:20 UTC, u1tnk commented on 06.bowling_object/game.rb
> +      if shot == 'X'
Shotクラスに strike_mark? で `X`を判定するメソッドがあるのに、ここで別途判定するのは良くないです。

2023-12-08 15:20 UTC, u1tnk commented on 06.bowling_object/game.rb
> +        @frames << Frame.new('X', '0')
ちょっと細かいですが、shotに X が入っているので shotを入れる方が自然ですね。

2023-12-11 06:00 UTC, a-terumoto-gs commented on 06.bowling_object/shot.rb
> +  attr_reader :mark
この変数を呼ぶ箇所はなかったので削除しました

2023-12-12 00:26 UTC, a-terumoto-gs commented on 06.bowling_object/game.rb
> +        @frames << Frame.new('X', '0')
修正しました

2023-12-12 01:19 UTC, a-terumoto-gs commented on 06.bowling_object/game.rb
> +      if shot == 'X'
strike_mark? を使用する形に修正しました

2023-12-12 01:48 UTC, a-terumoto-gs commented on 06.bowling_object/game.rb
> +  def initialize(game_shot)
命名を再検討し変更しました

また、こちらのメソッドで行っていたことをFrameクラスに行うように変更しました。

2023-12-12 02:20 UTC, a-terumoto-gs commented on 06.bowling_object/game.rb
> +    while index < game_shots.length
eachを使う形に修正しました

2023-12-12 16:50 UTC, u1tnk requested changes

2023-12-12 16:50 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +    play_result_split = play_result.gsub(/X,/, 'X,0,').split(',')
ここのXの判定も strike_markを使って実装するようにして欲しいです。
`X` がstrikeを表すことを知ってるのはShotだけにしたいですね。

2023-12-12 16:50 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +    (0...play_result_split.length).step(2).each do |index|
この処理だと 10フレームで3投したときは実際には存在しない11フレーム目を作って全部足した結果うまく動くんだと思います。
このプラクティスの仕様内だと辻褄はあうのですが、結果的に辻褄があったコードは変更に弱いです。
3投するパターンも取り込んで10frame内で処理できるようにしてみてください。

2023-12-12 16:50 UTC, u1tnk commented on 06.bowling_object/game.rb
> +play_result = Game.new(ARGV[0])
ここの変数だけだったら良いかとも思ったのですが、 play_result が他の箇所では「引数で受けとったもの」になっています。
表記ゆれという意味でも `Game.new` したとき複数あるなどの事情が無ければ `game` 変数に入れるのが自然なことから `game` にした方が良いと思います。

2023-12-13 04:33 UTC, a-terumoto-gs commented on 06.bowling_object/game.rb
> +play_result = Game.new(ARGV[0])
`game`に変更しました！

2023-12-13 08:04 UTC, a-terumoto-gs commented on 06.bowling_object/frame.rb
> +    play_result_split = play_result.gsub(/X,/, 'X,0,').split(',')
ロジックを見直してこの処理自体をなくしました。

2023-12-13 09:24 UTC, a-terumoto-gs commented on 06.bowling_object/frame.rb
> +    (0...play_result_split.length).step(2).each do |index|
10フレーム目を別で処理するようにしました。
それを受けて全体的にロジックを変更しました。

2023-12-15 01:33 UTC, u1tnk requested changes
前にもちょっと指摘したと思いますが、オブジェクト指向(とruby)に慣れてる人は

- 変数名game → Gameクラスのインスタンス
- 変数名 xxx_shots → Shotクラスのインスタンスの配列

と自然に考えてしまうので、その法則から外れると混乱するので避けるようにしましょう。
引数として入ってきた「カンマ区切りの一投ごとの数値の文字列」が定まってなさそうですが、Shotに渡すときに mark という名前を使っているので合わせれば統一性が出ると思います。

業務プログラマにとって「読みやすさ」というのはとても大事な部分なので混乱を招かないよう細部まで気を使うようにしましょう 💪

2023-12-15 01:33 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +  def self.game_result_adjustment(game)
ここも変数名が gameで Gameクラスのインスタンスでは無く誤解を招くので変数名を再検討してください。

2023-12-15 01:33 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +    game_split = []
変数は基本名詞にした方が良いですね。 gameが適当では無いですが、 splitted_xxxx のようにしましょう。

2023-12-15 10:22 UTC, a-terumoto-gs commented on 06.bowling_object/frame.rb
> +  def self.game_result_adjustment(game)
1投をmarkとして扱っているのでそのまとまりということでmarksで統一しようと考えました。
よってgameを使っていた箇所において変数名をmarksに統一しました。

2023-12-15 10:23 UTC, a-terumoto-gs commented on 06.bowling_object/frame.rb
> +    game_split = []
上記の変更を受けてsplitted_marksに変更しました。

2023-12-17 16:01 UTC, u1tnk requested changes
すみません、今回コメントした場所前回コメントしたと思っていたのですが、ミスで反映されなかったようです。

markを早めにShotにしてそのままShotとして使うようにするともうちょっとスッキリするのでやってみてください。

2023-12-17 16:01 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +        if Shot.new(mark).strike_mark?
こちらShotクラスのインスタンスを作ってメソッド呼んでインスタンス捨てているのでただのメソッドを使っているだけになっちゃっています。
Shotクラスのインスタンスはmarkを含んでいるのでmarkからShotにしたらそのままShotとして持っていた方が良いです。

2023-12-20 04:45 UTC, a-terumoto-gs commented on 06.bowling_object/frame.rb
> +        if Shot.new(mark).strike_mark?
Shot.new(mark)をそのままshotとして保持するようにしました。

2023-12-28 07:02 UTC, u1tnk requested changes

2023-12-28 07:02 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +    shots.each do |current_shot|
```
複数形.each do |単数形|
```

はイディオムなので

```
shots.each do |shot|
```

で大丈夫です。

2023-12-28 07:02 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +  def self.marks_adjustment(marks)
この名前は今は不適当ですね。
そもそも adjustment もちょっと曖昧です。
結果が splitted_shots なのであれば その語彙と一致させると良いと思います。

2023-12-28 07:02 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +    (0...18).step(2).each do |index|
splitted_shotsが既に各frameごとのshotの配列が入ってるんですよね？

そうであれば全部mapでFrameにするだけじゃないかと思います。

ということで、ここが整理されれば marks_adjustmentも不要になるかもですね。

2023-12-28 08:35 UTC, a-terumoto-gs commented on 06.bowling_object/frame.rb
> +    shots.each do |current_shot|
`current_shot`を`shot`に修正しました

2023-12-28 09:34 UTC, a-terumoto-gs commented on 06.bowling_object/frame.rb
> +  def self.marks_adjustment(marks)
markをsplitted_shotsに変形するメソッドということで、`convert_to_splitted_shots`に変更しました。

2023-12-28 09:35 UTC, a-terumoto-gs commented on 06.bowling_object/frame.rb
> +    (0...18).step(2).each do |index|
処理を少し整理してmapを使う形式にしました。

2023-12-28 15:08 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +  def self.marks_adjustment(marks)
元がmarksなのは 引数から分かりますし、splitされている=配列にされているのは `shots` と複数形になっている事で分かるので splittedは不要かなと思います。

2023-12-28 15:10 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +    (0...18).step(2).each do |index|
こちら frame分割の処理は mapになってなさそうなのですが、どこの事でしょうか？

2024-01-03 23:51 UTC, a-terumoto-gs commented on 06.bowling_object/frame.rb
> +  def self.marks_adjustment(marks)
`convert_to_shots`に変更しました。

2024-01-03 23:52 UTC, a-terumoto-gs commented on 06.bowling_object/frame.rb
> +    (0...18).step(2).each do |index|
このコメントに該当する修正の修正の内容を含めたコメントではありませんでした。
出来ていませんでした。訂正します。

2024-01-05 15:20 UTC, u1tnk approved these changes

2024-01-11 04:34 UTC, merged